// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// digest
int digest(const int salt, const RawVector& Txt);
RcppExport SEXP _hbmPRNG_digest(SEXP saltSEXP, SEXP TxtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type salt(saltSEXP);
    Rcpp::traits::input_parameter< const RawVector& >::type Txt(TxtSEXP);
    rcpp_result_gen = Rcpp::wrap(digest(salt, Txt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hbmPRNG_digest", (DL_FUNC) &_hbmPRNG_digest, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_hbmPRNG(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
